server:
  servlet:
    context-path: /indicadorfilmes

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

indicadorfilmes:
  clima:
    apikey: ${CLIMA_API_KEY:b0c5a158058aa6cdfb3bab2246530cf2}
    units: metric
    server: https://api.openweathermap.org/data/2.5
  filme:
    token: ${FILME_TOKEN:Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZjM3ZGUzMzQ2YjM0ZmEyZjU1OWIyNzUxYTU1MWU3ZiIsInN1YiI6IjY0OTIyYTlkODUwMDVkMDBlODc3Njc0MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.E2VBsqmW7FLpDlWxO7KBJtxUS_fBfGMUojSGNToqK4I}
    server: https://api.themoviedb.org

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
    org.hibernate: ${LOG_LEVEL:INFO}
    com.desafio.indicadorfilmes: ${LOG_LEVEL:INFO}